# Generated by Django 2.0.4 on 2018-05-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partidasGanadas', models.IntegerField()),
                ('partidasPerdidas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partidasGanadas', models.IntegerField()),
                ('partidasPerdidas', models.IntegerField()),
                ('caster', models.ManyToManyField(to='estadisticas.Caster')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rango', models.IntegerField()),
                ('elo', models.IntegerField()),
                ('partidasGanadas', models.IntegerField()),
                ('partidasPerdidas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Jugador1', models.IntegerField()),
                ('ID_Jugador2', models.IntegerField()),
                ('ID_Faccion1', models.IntegerField()),
                ('ID_Faccion2', models.IntegerField()),
                ('ID_Caster1', models.IntegerField()),
                ('ID_Caster2', models.IntegerField()),
            ],
        ),
    ]
