# Generated by Django 2.0.4 on 2018-05-01 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faccion',
            name='caster',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Caster',
        ),
        migrations.DeleteModel(
            name='Faccion',
        ),
    ]
