# Generated by Django 2.0.4 on 2018-05-01 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_auto_20180501_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
