# Generated by Django 2.0.4 on 2018-05-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estadisticas', '0003_delete_partida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('partidas_ganadas', models.PositiveIntegerField(verbose_name='Partidas Ganadas')),
                ('partidas_perdidas', models.PositiveIntegerField(verbose_name='Partidas Perdidas')),
            ],
            options={
                'verbose_name': 'Caster',
                'verbose_name_plural': 'Casters',
            },
        ),
        migrations.CreateModel(
            name='Faccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('partidas_ganadas', models.PositiveIntegerField(verbose_name='Partidas Ganadas')),
                ('partidas_perdidas', models.PositiveIntegerField(verbose_name='Partidas Perdidas')),
                ('caster', models.ManyToManyField(to='estadisticas.Caster')),
            ],
            options={
                'verbose_name': 'Faccion',
                'verbose_name_plural': 'Facciones',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('rango', models.PositiveIntegerField(verbose_name='Rango')),
                ('elo', models.PositiveIntegerField(verbose_name='Elo')),
                ('partidas_ganadas', models.PositiveIntegerField(verbose_name='Partidas Ganadas')),
                ('partidas_perdidas', models.PositiveIntegerField(verbose_name='Partidas Perdidas')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caster1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_caster', to='estadisticas.Caster')),
                ('caster2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_caster', to='estadisticas.Caster')),
                ('faccion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_facction', to='estadisticas.Faccion')),
                ('faccion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_facction', to='estadisticas.Faccion')),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to='estadisticas.Jugador')),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_player', to='estadisticas.Jugador')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
