# Generated by Django 2.0.4 on 2018-05-01 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jugador', '0001_initial'),
        ('faccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caster1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to='faccion.Caster')),
                ('caster2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_player', to='faccion.Caster')),
                ('faccion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to='faccion.Faccion')),
                ('faccion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_player', to='faccion.Faccion')),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_player', to='jugador.Jugador')),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_player', to='jugador.Jugador')),
            ],
        ),
    ]
